//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CartellaOrtodontica.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CM_INVOICEEntities1 : DbContext
    {
        public CM_INVOICEEntities1()
            : base("name=CM_INVOICEEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_CARTELLA_ORTODONTICA_DATI_CLINICI> T_CARTELLA_ORTODONTICA_DATI_CLINICI { get; set; }
        public virtual DbSet<T_LISTINO_PROCEDURE> T_LISTINO_PROCEDURE { get; set; }
        public virtual DbSet<T_LISTINO_RAGGRUPPAMENTI> T_LISTINO_RAGGRUPPAMENTI { get; set; }
        public virtual DbSet<T_LISTINO_SOTTOPROCEDURE> T_LISTINO_SOTTOPROCEDURE { get; set; }
        public virtual DbSet<T_CARTELLA_ORTODONTICA_RAGGRUPPAMENTI> T_CARTELLA_ORTODONTICA_RAGGRUPPAMENTI { get; set; }
        public virtual DbSet<T_LISTINO_PROCEDURE_SOTTOPROCEDURE> T_LISTINO_PROCEDURE_SOTTOPROCEDURE { get; set; }
        public virtual DbSet<T_CARTELLA_ORTODONTICA_SOTTOPROCEDURE> T_CARTELLA_ORTODONTICA_SOTTOPROCEDURE { get; set; }
        public virtual DbSet<T_TRATTAMENTI> T_TRATTAMENTI { get; set; }
        public virtual DbSet<T_ANAGRAFICA_PAZIENTI> T_ANAGRAFICA_PAZIENTI { get; set; }
        public virtual DbSet<ANM_AllergieFarmacologiche> ANM_AllergieFarmacologiche { get; set; }
        public virtual DbSet<ANM_FarmaciAssunti> ANM_FarmaciAssunti { get; set; }
        public virtual DbSet<ANM_Patologie> ANM_Patologie { get; set; }
        public virtual DbSet<T_TRATTAMENTI_NOTE> T_TRATTAMENTI_NOTE { get; set; }
        public virtual DbSet<T_CARTELLA_ORTODONTICA_PROCEDURE> T_CARTELLA_ORTODONTICA_PROCEDURE { get; set; }
        public virtual DbSet<T_AGENDA_APPUNTAMENTI> T_AGENDA_APPUNTAMENTI { get; set; }
        public virtual DbSet<T_PRESCRIZIONE> T_PRESCRIZIONE { get; set; }
        public virtual DbSet<T_ANAGRAFICA_FORNITORI> T_ANAGRAFICA_FORNITORI { get; set; }
        public virtual DbSet<T_CARTELLA_ORTODONTICA_REFERTAZIONE> T_CARTELLA_ORTODONTICA_REFERTAZIONE { get; set; }
        public virtual DbSet<T_STUDI> T_STUDI { get; set; }
        public virtual DbSet<T_SETUP> T_SETUP { get; set; }
        public virtual DbSet<T_PRESC_DETTAGLIO> T_PRESC_DETTAGLIO { get; set; }
    }
}
