//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CartellaOrtodontica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ANAGRAFICA_FORNITORI
    {
        public int CodFornitore { get; set; }
        public string Nome { get; set; }
        public string Cognome { get; set; }
        public string RagioneSociale { get; set; }
        public string Indirizzo { get; set; }
        public string Citta { get; set; }
        public string Provincia { get; set; }
        public string Nazione { get; set; }
        public string Cap { get; set; }
        public string Comune { get; set; }
        public string PartitaIva { get; set; }
        public string CodiceFiscale { get; set; }
        public string IntestazioneFatt { get; set; }
        public string NIMS { get; set; }
        public string TelefonoCasa { get; set; }
        public string TelefonoUfficio { get; set; }
        public string TelefonoCell { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public bool Odontotecnico { get; set; }
        public string ERP_NUM { get; set; }
        public byte[] LastEdit { get; set; }
        public Nullable<int> LastEditBy { get; set; }
    }
}
