//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CartellaOrtodontica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CARTELLA_ORTODONTICA_REFERTAZIONE
    {
        public int NTrattamento { get; set; }
        public string CodDato { get; set; }
        public string Valore { get; set; }
        public string Osservazioni { get; set; }
    
        public virtual T_CARTELLA_ORTODONTICA_DATI_CLINICI T_CARTELLA_ORTODONTICA_DATI_CLINICI { get; set; }
        public virtual T_TRATTAMENTI T_TRATTAMENTI { get; set; }
    }
}
