//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CartellaOrtodontica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CARTELLA_ORTODONTICA_DATI_CLINICI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_CARTELLA_ORTODONTICA_DATI_CLINICI()
        {
            this.T_CARTELLA_ORTODONTICA_REFERTAZIONE = new HashSet<T_CARTELLA_ORTODONTICA_REFERTAZIONE>();
        }
    
        public string CodDato { get; set; }
        public string Descrizione { get; set; }
        public bool In_Uso { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_CARTELLA_ORTODONTICA_REFERTAZIONE> T_CARTELLA_ORTODONTICA_REFERTAZIONE { get; set; }
    }
}
