//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CartellaOrtodontica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_LISTINO_PROCEDURE
    {
        public int CodProcedura { get; set; }
        public Nullable<int> CodRaggruppamento { get; set; }
        public string Descrizione { get; set; }
        public string Immagine { get; set; }
        public byte[] Foto { get; set; }
        public Nullable<int> ColPreventivato { get; set; }
        public Nullable<int> ColEseguito { get; set; }
        public Nullable<bool> In_uso { get; set; }
        public string Note { get; set; }
        public Nullable<int> Durata { get; set; }
        public Nullable<double> Prezzo { get; set; }
        public bool Generale { get; set; }
        public bool PrezzoImposto { get; set; }
        public string CodRegionale { get; set; }
        public Nullable<byte> TipoConto { get; set; }
        public string CodConto { get; set; }
        public Nullable<System.DateTime> DataIns { get; set; }
        public Nullable<System.DateTime> DataMod { get; set; }
        public byte[] LastEdit { get; set; }
        public Nullable<decimal> LastEditBy { get; set; }
        public string ERP_NUM { get; set; }
        public Nullable<decimal> QuotaVariabile { get; set; }
        public Nullable<decimal> ImportoFissoQV { get; set; }
        public string CodERP { get; set; }
        public Nullable<bool> Interna { get; set; }
        public Nullable<decimal> C__Quota_Variabile { get; set; }
        public Nullable<decimal> IVA { get; set; }
        public string Stato_Dente_Dopo_Esecuzione { get; set; }
        public Nullable<int> NumeroPianoDeiConti { get; set; }
    
        public virtual T_LISTINO_PROCEDURE T_LISTINO_PROCEDURE1 { get; set; }
        public virtual T_LISTINO_PROCEDURE T_LISTINO_PROCEDURE2 { get; set; }
        public virtual T_CARTELLA_ORTODONTICA_PROCEDURE T_CARTELLA_ORTODONTICA_PROCEDURE { get; set; }
    }
}
