//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CartellaOrtodontica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_STUDI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_STUDI()
        {
            this.T_ANAGRAFICA_PAZIENTI = new HashSet<T_ANAGRAFICA_PAZIENTI>();
        }
    
        public int ID { get; set; }
        public string Descrizione { get; set; }
        public byte[] LastEdit { get; set; }
        public Nullable<decimal> LastEditBy { get; set; }
        public string CartellaImmagini { get; set; }
        public string DirettoreSanitario { get; set; }
        public string IndirizzoStruttura { get; set; }
        public string NomeStruttura { get; set; }
        public int Colore { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_ANAGRAFICA_PAZIENTI> T_ANAGRAFICA_PAZIENTI { get; set; }
    }
}
