//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CartellaOrtodontica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_LISTINO_RAGGRUPPAMENTI
    {
        public int CodRaggruppamento { get; set; }
        public Nullable<int> CodSuperRagg { get; set; }
        public bool RaggruppamentoGenerico { get; set; }
        public string Descrizione { get; set; }
        public Nullable<double> CostoOrario { get; set; }
        public Nullable<double> CostoOrarioAss { get; set; }
        public Nullable<System.DateTime> DataIns { get; set; }
        public Nullable<System.DateTime> DataMod { get; set; }
        public string Simbolo { get; set; }
        public Nullable<int> Priorita { get; set; }
        public Nullable<int> Colore { get; set; }
        public byte[] LastEdit { get; set; }
        public Nullable<decimal> LastEditBy { get; set; }
        public string ERP_NUM { get; set; }
        public bool InUso { get; set; }
    
        public virtual T_CARTELLA_ORTODONTICA_RAGGRUPPAMENTI T_CARTELLA_ORTODONTICA_RAGGRUPPAMENTI { get; set; }
    }
}
