//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CartellaOrtodontica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_LISTINO_SOTTOPROCEDURE
    {
        public int CodSottoprocedura { get; set; }
        public Nullable<int> CodPrestazione { get; set; }
        public string Descrizione { get; set; }
        public string Immagine { get; set; }
        public byte[] Foto { get; set; }
        public Nullable<bool> Mancato { get; set; }
        public Nullable<bool> In_uso { get; set; }
        public Nullable<bool> Assistente { get; set; }
        public string TipoEseguito { get; set; }
        public string Note { get; set; }
        public string Frase { get; set; }
        public Nullable<bool> SMS { get; set; }
        public Nullable<bool> Generale { get; set; }
        public Nullable<bool> Accorpamento { get; set; }
        public Nullable<bool> Lunghezza { get; set; }
        public Nullable<bool> Diametro { get; set; }
        public Nullable<bool> Colore { get; set; }
        public Nullable<bool> NumeroProg { get; set; }
        public string Conformita { get; set; }
        public Nullable<bool> UsaPrezzo { get; set; }
        public Nullable<bool> PrezzoGen { get; set; }
        public string PerPiuDenti { get; set; }
        public Nullable<bool> Diretto { get; set; }
        public Nullable<int> Durata { get; set; }
        public Nullable<double> PrezzoPrestazioni { get; set; }
        public Nullable<double> PrezzoVassoio { get; set; }
        public Nullable<double> PrezzoPrescrizioni { get; set; }
        public string CodRegionale { get; set; }
        public Nullable<byte> TipoConto { get; set; }
        public string CodConto { get; set; }
        public Nullable<System.DateTime> DataIns { get; set; }
        public Nullable<System.DateTime> DataMod { get; set; }
        public byte[] LastEdit { get; set; }
        public Nullable<decimal> LastEditBy { get; set; }
        public string ERP_NUM { get; set; }
        public Nullable<decimal> QuotaVariabile { get; set; }
        public Nullable<decimal> ImportoFissoQV { get; set; }
        public string CodERP { get; set; }
        public Nullable<bool> Interna { get; set; }
        public Nullable<int> Categoria { get; set; }
        public Nullable<int> Vassoio { get; set; }
        public Nullable<bool> GestioneMateriale { get; set; }
        public Nullable<bool> Medico { get; set; }
        public string PrimaVisita { get; set; }
        public bool ApprofondimentoDiagnostici { get; set; }
        public string UnaSolaOccorrenzaPer { get; set; }
    
        public virtual T_CARTELLA_ORTODONTICA_SOTTOPROCEDURE T_CARTELLA_ORTODONTICA_SOTTOPROCEDURE { get; set; }
    }
}
