//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CartellaOrtodontica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_LISTINO_PROCEDURE_SOTTOPROCEDURE
    {
        public int ID { get; set; }
        public int CodProcedura { get; set; }
        public int CodSottoprocedura { get; set; }
        public Nullable<int> Durata { get; set; }
        public Nullable<int> NumeroAppuntamento { get; set; }
        public Nullable<int> Progressione { get; set; }
        public Nullable<bool> PiuDenti { get; set; }
        public string SingPiu { get; set; }
        public byte[] LastEdit { get; set; }
        public Nullable<decimal> LastEditBy { get; set; }
    }
}
