//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CartellaOrtodontica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PRESCRIZIONE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_PRESCRIZIONE()
        {
            this.T_PRESC_DETTAGLIO = new HashSet<T_PRESC_DETTAGLIO>();
        }
    
        public int CodPrescrizione { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<int> CodicePaziente { get; set; }
        public string Numero { get; set; }
        public Nullable<int> CodiceLaboratorio { get; set; }
        public int NumeroPiano { get; set; }
        public Nullable<int> CodiceMedico { get; set; }
        public Nullable<System.DateTime> Consegna { get; set; }
        public Nullable<System.DateTime> ConsegnaOre { get; set; }
        public string ColoreDenti { get; set; }
        public string Allergie { get; set; }
        public string Intolleranze { get; set; }
        public string Problematiche { get; set; }
        public string Handicap { get; set; }
        public string ArcoFacciale { get; set; }
        public string RegOcclusali { get; set; }
        public string Impronte { get; set; }
        public Nullable<System.DateTime> Rilevate { get; set; }
        public string Disinfettate { get; set; }
        public string Imballaggio { get; set; }
        public Nullable<double> Prezzo { get; set; }
        public string Appunti { get; set; }
        public string Firma { get; set; }
        public string NotePers { get; set; }
        public string NumOrdine { get; set; }
        public Nullable<bool> Shipped { get; set; }
        public string InseritoDa { get; set; }
        public string UltimaModifica { get; set; }
        public byte[] LastEdit { get; set; }
        public Nullable<int> LastEditBy { get; set; }
        public Nullable<int> CodImportazione { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_PRESC_DETTAGLIO> T_PRESC_DETTAGLIO { get; set; }
    }
}
