//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CartellaOrtodontica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TRATTAMENTI_NOTE
    {
        public int Codnota { get; set; }
        public int Codpaziente { get; set; }
        public string Eseguito { get; set; }
        public string Daeseguire { get; set; }
        public string OsservazioniGenerali { get; set; }
        public System.DateTime DataIns { get; set; }
        public Nullable<System.DateTime> DataMod { get; set; }
        public string InseritoDa { get; set; }
        public string UltimaModifica { get; set; }
        public Nullable<int> InseritoDaCodMedico { get; set; }
        public int NumPianoDiCura { get; set; }
        public Nullable<int> NTrattamento { get; set; }
    }
}
