//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CartellaOrtodontica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TRATTAMENTI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_TRATTAMENTI()
        {
            this.T_CARTELLA_ORTODONTICA_REFERTAZIONE = new HashSet<T_CARTELLA_ORTODONTICA_REFERTAZIONE>();
        }
    
        public int NTrattamento { get; set; }
        public string Descrizione { get; set; }
        public int CodPaziente { get; set; }
        public int NumPianoDiCura { get; set; }
        public Nullable<int> NPreventivo { get; set; }
        public Nullable<double> TotalePreventivo { get; set; }
        public Nullable<int> CodListino { get; set; }
        public Nullable<int> CodConvenzione { get; set; }
        public Nullable<int> CodSuperRaggruppamento { get; set; }
        public Nullable<int> CodRaggruppamento { get; set; }
        public Nullable<int> CodProceduraPadre { get; set; }
        public Nullable<int> CodProcedura { get; set; }
        public Nullable<int> CodProceduraSottoproceduraId { get; set; }
        public Nullable<int> CodSottoprocedura { get; set; }
        public Nullable<int> CodMicroprocedura { get; set; }
        public string CodiceStato { get; set; }
        public Nullable<int> CodMedico { get; set; }
        public Nullable<int> CodPadre { get; set; }
        public Nullable<int> Dente_1 { get; set; }
        public Nullable<int> Dente_2 { get; set; }
        public Nullable<int> Ndenti { get; set; }
        public Nullable<double> Prezzo { get; set; }
        public Nullable<double> Incassato { get; set; }
        public Nullable<System.DateTime> DataPreventivo { get; set; }
        public string Nota { get; set; }
        public Nullable<System.DateTime> DataEsecuzione { get; set; }
        public Nullable<int> NumeroAppuntamento { get; set; }
        public Nullable<int> Progressione { get; set; }
        public Nullable<int> ProgressioneProcedura { get; set; }
        public Nullable<bool> AppCam { get; set; }
        public Nullable<int> Accettato { get; set; }
        public bool Pagato { get; set; }
        public Nullable<bool> Fatturato { get; set; }
        public Nullable<int> CodLaboratorio { get; set; }
        public Nullable<decimal> Tipo { get; set; }
        public Nullable<double> Lunghezza { get; set; }
        public Nullable<double> Diametro { get; set; }
        public bool Concordato { get; set; }
        public Nullable<int> CodIncasso { get; set; }
        public Nullable<double> PrezzoListinoTeorico { get; set; }
        public Nullable<double> PrezzoListinoCommerciale { get; set; }
        public Nullable<double> PrezzoConc { get; set; }
        public Nullable<double> PrezzoDaConcordare { get; set; }
        public Nullable<double> PrezzoPaziente { get; set; }
        public Nullable<double> PrezzoEnte { get; set; }
        public bool Generico { get; set; }
        public bool Cancellato { get; set; }
        public Nullable<bool> ConteggiaConcordato { get; set; }
        public bool Modificato { get; set; }
        public string InseritoDa { get; set; }
        public string UltimaModifica { get; set; }
        public System.DateTime DataIns { get; set; }
        public Nullable<System.DateTime> DataMod { get; set; }
        public byte[] LastEdit { get; set; }
        public Nullable<decimal> LastEditBy { get; set; }
        public Nullable<int> NTrattamento_Master { get; set; }
        public Nullable<int> CodImportazione { get; set; }
        public string ERP_NUM_PDC { get; set; }
        public string ERP_NUM_PDC_ROW { get; set; }
        public Nullable<double> ImportoSconto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_CARTELLA_ORTODONTICA_REFERTAZIONE> T_CARTELLA_ORTODONTICA_REFERTAZIONE { get; set; }
    }
}
